### ISSUE TITLE
Task #12576 for LeaderMobs v2.2.1 generated an exception

### ISSUE THREAD

**Issue by erkutay07** [xHexed/LeaderMobs#30]
it keeps spamming same warning message when mob spawns or dies

[20:56:27 WARN]: [LeaderMobs] Task #12576 for LeaderMobs v2.2.1 generated an exception
java.lang.NullPointerException: Cannot invoke "String.length()" because "replacement" is null
        at java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1014) ~[?:?]
        at java.util.regex.Matcher.appendReplacement(Matcher.java:997) ~[?:?]
        at java.util.regex.Matcher.replaceAll(Matcher.java:1181) ~[?:?]
        at com.github.xhexed.leadermobs.util.PluginUtil.getMobSpawnMessage(PluginUtil.java:26) ~[LeaderMobs-2.2.1.jar:?]
        at com.github.xhexed.leadermobs.manager.MobEventManager.lambda$handleMobSpawn$0(MobEventManager.java:47) ~[LeaderMobs-2.2.1.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at com.github.xhexed.leadermobs.manager.MobEventManager.lambda$handleMobSpawn$6(MobEventManager.java:48) ~[LeaderMobs-2.2.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-164]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-164]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-164]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-164]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-164]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-164]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-164]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by erkutay07** [comment]
nvm i figured out, it was happening because display was null in mythicmobs but when you use toggle command once the broadcast shows when its disabled and doesnt show when its enabled

**Comment by erkutay07** [comment]
and removing the damage-taken section breaks the plugin

**Comment by xHexed** [comment]
Yep im aware of these bugs, will fix them asap 😭

**Comment by xHexed** [comment]
I released an [update](https://github.com/xHexed/LeaderMobs/releases) that "should" fix your issues. lmk if the bugs still persists
